### ISSUE TITLE
Some of the 1210 practice sheets have the answers

### ISSUE THREAD

**Issue by ghseeli** [MareoRaft/MATH-Calc#4]
I noticed that the "Applications of first derivative - Peter" file has all the solutions in them; I think we should probably omit those solutions from being posted publicly. Thoughts @MareoRaft ?

**Comment by MareoRaft** [comment]
I have no preference.  Whatever you would like is okay by me.

**Comment by ghseeli** [comment]
Well, also, these are homework exercises Peter gives to his students. We don’t want to be giving away his answer keys.

**Comment by ghseeli** [comment]
I think there was only one sheet where the answers seemed problematic to have posted, and I have commented them out. I will inquire with Peter about the other solutions when I see him.

**Comment by ghseeli** [comment]
Peter said he ultimately did not care, so I will close this issue out.
